From the given Popular_Quotes.html, load the file ensuring the utf-8 encoding and do the following task using BeautifulSoup library in python.

1.	Extract the text from the <h1> tag and display it.
2.	Retrieve the text of the <title> tag, then display it in reverse order.
3.	What is the total number of <script> tags in the HTML?
4.	Extract all tags listed under the first quote by Oscar Wilde and print the tag with the most characters.
5.	Print the first 5 quotes along with their authors in the below given format:
Example:
Quote: “Be yourself; everyone else is already taken.” 
Author: Oscar Wilde
6.	Display the quotes that contain the word "accomplishment" in its text.
7.	Extract the number of likes for each quote and display them in ascending order.
8.	Find and print the names of authors who have more than one quote on the page.
9.	Create a DataFrame containing the quote, author name, and number of likes.

In [2]:
import bs4
import pandas as pd
fh=open('Popular_Quotes.html',encoding='utf8')
soup= bs4.BeautifulSoup(fh,'html.parser')

In [3]:
#1.	Extract the text from the <h1> tag and display it.
t=soup.find("h1").text.strip()
t

'Popular quotes'

In [4]:
#2.	Retrieve the text of the <title> tag, then display it in reverse order.
t=soup.find("title").text.strip()[::-1]
t

'setouQ ralupoP'

In [5]:
#3.	What is the total number of <script> tags in the HTML?
tag3= soup.find_all('script')
print(len(tag3))

28

In [6]:
#4.	Extract all tags listed under the first quote by Oscar Wilde and print the tag with the most characters.
tag4=soup.find('div', {'class':'greyText smallText left'}).text.strip().split()
maximum=0
for word in tag4:
    l=len(word)
    if l>maximum:
        maximum=l
        res=word
print(res)

misattributed-oscar-wilde,

In [7]:
# 5.	Print the first 5 quotes along with their authors in the below given format:
# Example:
# Quote: “Be yourself; everyone else is already taken.” 
# Author: Oscar Wilde

qt=[]
au=[]

for tag in soup.find_all('div',{'class':'quoteText'}):
    d=tag.text.strip()
    st=d.find("“")
    end=d.find("”")
    
    qt.append(d[st+1:end])
# print(qt)
print("\n\n")

for author in soup.find_all('span',{'class':'authorOrTitle'}):
    a=author.text.strip()
    au.append(a)
# print(au)

for i in range(len(qt)):
    print("Quote: ", qt[i])
    print("Author: ",au[i])
    print("-------------")

Quote:  Be yourself; everyone else is already taken.
Author:  Oscar Wilde
-------------
Quote:  I'm selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can't handle me at my worst, then you sure as hell don't deserve me at my best.
Author:  Marilyn Monroe
-------------
Quote:  So many books, so little time.
Author:  Frank Zappa
-------------
Quote:  Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.
Author:  Albert Einstein
-------------
Quote:  A room without books is like a body without a soul.
Author:  Marcus Tullius Cicero
-------------
Quote:  Be who you are and say what you feel, because those who mind don't matter, and those who matter don't mind.
Author:  Bernard M. Baruch
-------------
Quote:  You've gotta dance like there's nobody watching,Love like you'll never be hurt,Sing like there's nobody listening,And live like it's heaven on earth.
Author:  William W. Purkey
-------------
Quote:  You know you're in love when you can't fall asleep because reality is finally better than your dreams.
Author:  Dr. Seuss
-------------
Quote:  You only live once, but if you do it right, once is enough.
Author:  Mae West
-------------
Quote:  Be the change that you wish to see in the world.
Author:  Mahatma Gandhi
-------------
Quote:  In three words I can sum up everything I've learned about life: it goes on.
Author:  Robert Frost
-------------
Quote:  If you want to know what a man's like, take a good look at how he treats his inferiors, not his equals.
Author:  J.K. Rowling,
-------------
Quote:  Don’t walk in front of me… I may not followDon’t walk behind me… I may not leadWalk beside me… just be my friend
Author:  Albert Camus
-------------
Quote:  If you tell the truth, you don't have to remember anything.
Author:  Mark Twain
-------------
Quote:  Friendship ... is born at the moment when one man says to another "What! You too? I thought that no one but myself . . .
Author:  C.S. Lewis,
-------------
Quote:  I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.
Author:  Maya Angelou
-------------
Quote:  A friend is someone who knows all about you and still loves you.
Author:  Elbert Hubbard
-------------
Quote:  To live is the rarest thing in the world. Most people exist, that is all.
Author:  Oscar Wilde
-------------
Quote:  Always forgive your enemies; nothing annoys them so much.
Author:  Oscar Wilde
-------------
Quote:  Darkness cannot drive out darkness: only light can do that. Hate cannot drive out hate: only love can do that.
Author:  Martin Luther King Jr.,
-------------
Quote:  Live as if you were to die tomorrow. Learn as if you were to live forever.
Author:  Mahatma Gandhi
-------------
Quote:  We accept the love we think we deserve.
Author:  Stephen Chbosky,
-------------
Quote:  Without music, life would be a mistake.
Author:  Friedrich Nietzsche,
-------------
Quote:  I am so clever that sometimes I don't understand a single word of what I am saying.
Author:  Oscar Wilde,
-------------
Quote:  To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.
Author:  Ralph Waldo Emerson
-------------
Quote:  Here's to the crazy ones. The misfits. The rebels. The troublemakers. The round pegs in the square holes. The ones who see things differently. They're not fond of rules. And they have no respect for the status quo. You can quote them, disagree with them, glorify or vilify them. About the only thing you can't do is ignore them. Because they change things. They push the human race forward. And while some may see them as the crazy ones, we see genius. Because the people who are crazy enough to think they can change the world, are the ones who do.
Author:  Steve Jobs
-------------
Quote:  Insanity is doing the same thing, over and over again, but expecting different results.
Author:  Narcotics Anonymous
-------------
Quote:  I believe that everything happens for a reason. People change so that you can learn to let go, things go wrong so that you appreciate them when they're right, you believe lies so you eventually learn to trust no one but yourself, and sometimes good things fall apart so better things can fall together.
Author:  Marilyn Monroe
-------------
Quote:  It is better to be hated for what you are than to be loved for what you are not.
Author:  Andre Gide,
-------------
Quote:  Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.
Author:  H. Jackson Brown Jr.,
-------------

In [8]:
# 6.	Display the quotes that contain the word "accomplishment" in its text.
for i in qt:
    if 'accomplishment' in i:
        print(i)

To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.

In [9]:
# 7.	Extract the number of likes for each quote and display them in ascending order.
likes=[]
for li in soup.find_all('a',{'class':'smallText'}):
    data=li.text.strip().split()[0]
    likes.append(data)
likes.sort()
print(likes)

['100983', '108002', '113213', '117240', '124987', '127116', '128599', '133363', '146082', '147069', '162993', '172090', '59792', '61028', '61795', '64173', '67728', '69009', '71126', '73251', '74875', '77061', '77451', '80923', '83168', '83514', '87398', '87553', '90869', '92274']

In [10]:
# # 8.	Find and print the names of authors who have more than one quote on the page.
# l=[]
# for name in au:
#     if au.count(name) and name not in l:
#         l.append(name)
# print(l)

l = []
for name in au:
    # Safely check if they appear more than once AND aren't already tracked
    if au.count(name) > 1 and name not in l:
        l.append(name)
print(l)

['Oscar Wilde', 'Marilyn Monroe', 'Mahatma Gandhi']

In [11]:
# 9.	Create a DataFrame containing the quote, author name, and number of likes.

import pandas as pd

df=pd.DataFrame({"Quote":qt,
                "Author_name":au,
                "No_like":likes})
df

,Quote,Author_name,No_like
0,Be yourself; everyone else is already taken.,Oscar Wilde,100983
1,"I'm selfish, impatient and a little insecure. ...",Marilyn Monroe,108002
2,"So many books, so little time.",Frank Zappa,113213
3,Two things are infinite: the universe and huma...,Albert Einstein,117240
4,A room without books is like a body without a ...,Marcus Tullius Cicero,124987
5,"Be who you are and say what you feel, because ...",Bernard M. Baruch,127116
6,You've gotta dance like there's nobody watchin...,William W. Purkey,128599
7,You know you're in love when you can't fall as...,Dr. Seuss,133363
8,"You only live once, but if you do it right, on...",Mae West,146082
9,Be the change that you wish to see in the world.,Mahatma Gandhi,147069
10,In three words I can sum up everything I've le...,Robert Frost,162993
11,"If you want to know what a man's like, take a ...","J.K. Rowling,",172090
12,Don’t walk in front of me… I may not followDon...,Albert Camus,59792
13,"If you tell the truth, you don't have to remem...",Mark Twain,61028
14,Friendship ... is born at the moment when one ...,"C.S. Lewis,",61795
15,I've learned that people will forget what you ...,Maya Angelou,64173
16,A friend is someone who knows all about you an...,Elbert Hubbard,67728
17,To live is the rarest thing in the world. Most...,Oscar Wilde,69009
18,Always forgive your enemies; nothing annoys th...,Oscar Wilde,71126
19,Darkness cannot drive out darkness: only light...,"Martin Luther King Jr.,",73251
20,Live as if you were to die tomorrow. Learn as ...,Mahatma Gandhi,74875
21,We accept the love we think we deserve.,"Stephen Chbosky,",77061
22,"Without music, life would be a mistake.","Friedrich Nietzsche,",77451
23,I am so clever that sometimes I don't understa...,"Oscar Wilde,",80923
24,To be yourself in a world that is constantly t...,Ralph Waldo Emerson,83168
25,Here's to the crazy ones. The misfits. The reb...,Steve Jobs,83514
26,"Insanity is doing the same thing, over and ove...",Narcotics Anonymous,87398
27,I believe that everything happens for a reason...,Marilyn Monroe,87553
28,It is better to be hated for what you are than...,"Andre Gide,",90869
29,Twenty years from now you will be more disappo...,"H. Jackson Brown Jr.,",92274

------------------------------------------------------------------------------------------------

In [3]:
from bs4 import BeautifulSoup
import pandas as pd

#Simulating the uploaded HTML structure

html_content = open("index (1).html",encoding="utf-8")
soup = BeautifulSoup(html_content, 'html.parser')

In [ ]:
# Level 1: Basic Extraction
# Q1. Extract the title of the webpage.

# Expected Output

# TechKart - Static Product Website

print(soup.title.text)

TechKart - Static Product Website

In [ ]:
# Q2. Extract the main heading of the website.
# TechKart


print(soup.header.h1.text)

TechKart

In [ ]:
# Q3. Extract all navigation menu names.
# Home
# Products
# About
# Contact
# Amazon


navbar_links = soup.find('nav').find_all('a')
for link in navbar_links:
    print(link.text)

Home
Products
About
Contact
Amazon

In [ ]:
# Q4. Extract all hyperlinks (href) present in the navbar.

# Output:

# #home
# #products
# #about
# #contact
# https://www.amazon.in




navbar_links = soup.find('nav').find_all('a')
for link in navbar_links:
    print(link['href'])

#home
#products
#about
#contact
https://www.amazon.in

In [18]:
#lvl 2

In [ ]:
# Level 2: Product Information
# Q5. Extract names of all products.

# Output:

# Wireless Mouse
# Mechanical Keyboard
# Bluetooth Speaker
# Smart Watch



products = soup.find_all('div', class_='product-card')
for card in products:
    print(card.find('h3', class_='product-name').text)

Wireless Mouse
Mechanical Keyboard
Bluetooth Speaker
Smart Watch

In [ ]:
# Q6. Extract prices of all products.

# Output:

# ₹799
# ₹2499
# ₹1599
# ₹3499


products = soup.find_all('div', class_='product-card')
for card in products:
    print(card.find('p', class_='price').text)

₹799
₹2499
₹1599
₹3499

In [ ]:
# Q7. Extract ratings of all products.

# Output:

# 4.3 ★
# 4.7 ★
# 4.1 ★
# 4.5 ★



products = soup.find_all('div', class_='product-card')
for card in products:
    # Cleaning up the "Rating: " prefix using .replace()
    rating_text = card.find('p', class_='rating').text.replace("Rating: ", "")
    print(rating_text)

4.3 ★
4.7 ★
4.1 ★
4.5 ★

In [ ]:
# Q8. Extract seller names.

# Output:

# TechWorld
# KeyMaster
# SoundHub
# GadgetZone



products = soup.find_all('div', class_='product-card')
for card in products:
    seller_text = card.find('p', class_='seller').text.replace("Seller: ", "")
    print(seller_text)

TechWorld
KeyMaster
SoundHub
GadgetZone

In [ ]:
# Q9. Extract stock status of all products.

# Output:

# In Stock
# In Stock
# Out of Stock
# In Stock


products = soup.find_all('div', class_='product-card')
for card in products:
    print(card.find('p', class_='stock').text)

In Stock
In Stock
Out of Stock
In Stock

In [24]:
#lvl 3

In [ ]:
# Level 3: Working with Attributes
# Q10. Extract all Product IDs.

# Output:

# 101
# 102
# 103
# 104

# Hint:

# product['data-id']



products = soup.find_all('div', class_='product-card')
for card in products:
    print(card['data-id'])

101
102
103
104

In [ ]:
# Q11. Extract image URLs.

# Hint:

# img['src']



products = soup.find_all('div', class_='product-card')
for card in products:
    print(card.find('img')['src'])

https://via.placeholder.com/200x150?text=Mouse
https://via.placeholder.com/200x150?text=Keyboard
https://via.placeholder.com/200x150?text=Speaker
https://via.placeholder.com/200x150?text=Smart+Watch

In [ ]:
# Q12. Extract "View Deal" links.

# Hint:

# card.find('a')['href']


products = soup.find_all('div', class_='product-card')
for card in products:
   print(card.find('a')['href'])

https://www.amazon.in/s?k=wireless+mouse
https://www.amazon.in/s?k=mechanical+keyboard
https://www.amazon.in/s?k=bluetooth+speaker
https://www.amazon.in/s?k=smart+watch

In [38]:
# 2nd option to search 

# Safe approach: Only look inside the product cards
products = soup.find_all('div', class_='product-card')

for card in products:
    # This guarantees you only get the "View Deal" link for that specific product
    deal_link = card.find('a', target="_blank")
    print(deal_link['href'])

https://www.amazon.in/s?k=wireless+mouse
https://www.amazon.in/s?k=mechanical+keyboard
https://www.amazon.in/s?k=bluetooth+speaker
https://www.amazon.in/s?k=smart+watch

In [28]:
#lvl 4

In [ ]:
# Level 4: Filtering Questions
# Q13. Display only products that are "In Stock".

# Expected:

# Wireless Mouse
# Mechanical Keyboard
# Smart Watch




products = soup.find_all('div', class_='product-card')
for card in products:
    stock_status = card.find('p', class_='stock')
    if 'available' in stock_status['class']:
        print(card.find('h3').text)

Wireless Mouse
Mechanical Keyboard
Smart Watch

In [ ]:
# Q14. Display only products whose category is Accessories.

# Expected:

# Wireless Mouse
# Mechanical Keyboard



products = soup.find_all('div', class_='product-card')
for card in products:
    category = card.find('p', class_='category').text
    if "Accessories" in category:
        print(card.find('h3').text)

Wireless Mouse
Mechanical Keyboard

In [11]:
# Q15. Find the most expensive product.

# Expected:

# Smart Watch
# ₹3499




products = soup.find_all('div', class_='product-card')
highest_price = 0
expensive_product = ""

for card in products:
    price_str = card.find('p', class_='price').text[1:]
    price_num = int(price_str)
    
    if price_num > highest_price:
        highest_price = price_num
        expensive_product = card.find('h3').text

print(expensive_product)
print(f"₹{highest_price}")

Smart Watch
₹3499

In [ ]:
# Q16. Find the cheapest product.

# Expected:

# Wireless Mouse
# ₹799




products = soup.find_all('div', class_='product-card')
lowest_price = float('inf') # Set initial value to infinity
cheapest_product = ""

for card in products:
    price_str = card.find('p', class_='price').text
    price_num = int(price_str.replace('₹', ''))
    
    if price_num < lowest_price:
        lowest_price = price_num
        cheapest_product = card.find('h3').text

print(cheapest_product)
print(f"₹{lowest_price}")

Wireless Mouse
₹799

In [39]:
# 2nd option

products = soup.find_all('div', class_='product-card')
lowest_price = 9999999  # Setting a massive dummy maximum
cheapest_product = ""

for card in products:
    price_str = card.find('p', class_='price').text
    price_num = int(price_str.replace('₹', ''))
    
    if price_num < lowest_price:
        lowest_price = price_num
        cheapest_product = card.find('h3').text

print(cheapest_product)
print(f"₹{lowest_price}")

Wireless Mouse
₹799

In [ ]:
# Q17. Find product with highest rating.

# Expected:

# Mechanical Keyboard
# 4.7




products = soup.find_all('div', class_='product-card')
highest_rating = 0.0
top_rated_product = ""

for card in products:
    rating_str = card.find('p', class_='rating').text.replace("Rating: ", "").replace(" ★", "")
    rating_num = float(rating_str)
    
    if rating_num > highest_rating:
        highest_rating = rating_num
        top_rated_product = card.find('h3').text

print(top_rated_product)
print(highest_rating)

Mechanical Keyboard
4.7

In [34]:
#lvl 5

In [21]:
# Level 5: DataFrame Creation



# Q.18
# Create a DataFrame containing



products = soup.find_all('div', class_='product-card')
product_list = []

for card in products:
    data = {
        "Product ID": card['data-id'],
        "Name": card.find('h3').text,
        "Category": card.find('p', class_='category').text.replace("Category: ", ""),
        "Price": card.find('p', class_='price').text,
        "Rating": card.find('p', class_='rating').text.replace("Rating: ", ""),
        "Stock Status": card.find('p', class_='stock').text,
        "Seller": card.find('p', class_='seller').text.replace("Seller: ", ""),
        "Image URL": card.find('img')['src'],
        "Deal Link": card.find('a')['href']
    }
    product_list.append(data)

# Create DataFrame
df = pd.DataFrame(product_list)

# Display DataFrame
df

,Product ID,Name,Category,Price,Rating,Stock Status,Seller,Image URL,Deal Link
0,101,Wireless Mouse,Accessories,₹799,4.3 ★,In Stock,TechWorld,https://via.placeholder.com/200x150?text=Mouse,https://www.amazon.in/s?k=wireless+mouse
1,102,Mechanical Keyboard,Accessories,₹2499,4.7 ★,In Stock,KeyMaster,https://via.placeholder.com/200x150?text=Keyboard,https://www.amazon.in/s?k=mechanical+keyboard
2,103,Bluetooth Speaker,Audio,₹1599,4.1 ★,Out of Stock,SoundHub,https://via.placeholder.com/200x150?text=Speaker,https://www.amazon.in/s?k=bluetooth+speaker
3,104,Smart Watch,Wearables,₹3499,4.5 ★,In Stock,GadgetZone,https://via.placeholder.com/200x150?text=Smart...,https://www.amazon.in/s?k=smart+watch

In [19]:
products =soup.find_all('div', class_='product-card')

lowest_price = 999999
lowest_product = ""

for card in products:
    name = card.find('h3').text
    price_str = card.find('p', class_='price').text
    price = int(price_str[1:])   # remove ₹

    if price < lowest_price:
        lowest_price = price
        lowest_product = name

print(lowest_product)
print("₹" + str(lowest_price))

Wireless Mouse
₹799