# get_dummies(data, columns, prefix=None, drop_first=False)
The get_dummies function is used to convert categorical variables into dummy or indicator variables. A dummy or indicator variable can have a value of 0 or 1.

In [4]:
import pandas as pd
s = pd.Series(['A','X','E','B','D'])
res = pd.get_dummies(s)
print(res)

       A      B      D      E      X
0   True  False  False  False  False
1  False  False  False  False   True
2  False  False  False   True  False
3  False   True  False  False  False
4  False  False   True  False  False

In [6]:
import pandas as pd
s = pd.Series(['A','X','E','B','D'])
res = pd.get_dummies(s, drop_first=True, prefix='AA' )
print(res)

    AA_B   AA_D   AA_E   AA_X
0  False  False  False  False
1  False  False  False   True
2  False  False   True  False
3   True  False  False  False
4  False   True  False  False

In [9]:
data = {
'Area': [500, 750, 1000, 1200, 1500],
'Price': ['Low', 'Low', 'MId', 'High', 'High']
}
df = pd.DataFrame(data)

res = pd.get_dummies(df, prefix='AA' )
print(res)

   Area  AA_High  AA_Low  AA_MId
0   500    False    True   False
1   750    False    True   False
2  1000    False   False    True
3  1200     True   False   False
4  1500     True   False   False

In [16]:
data = {
'Area': [500, 750, 1000, 1200, 1500],
'Price': ['Low', 'Low', 'MId', 'High', 'High'],
'Category':['A','B','A','B','A']
}
df = pd.DataFrame(data)

res = pd.get_dummies(df, prefix='AA' ,columns=['Price'])
print(res)

   Area Category  AA_High  AA_Low  AA_MId
0   500        A    False    True   False
1   750        B    False    True   False
2  1000        A    False   False    True
3  1200        B     True   False   False
4  1500        A     True   False   False

# np.where(condition, value_if_true, value_if_false)
numpy.where() is used for conditional selection and replacement in NumPy arrays. It can be used to:
1. Find indices that satisfy a condition
2. Build a new array by choosing values from two options depending on a condition.

In [10]:
import numpy as np
arr = np.array([10, 15, 20, 25, 30])
result = np.where(arr > 20)
print(result)

(array([3, 4]),)

In [12]:
data = {'Marks': [10, 15, 20, 25, 30]}
df= pd.DataFrame(data)
df['category'] = np.where(df['Marks'] > 20, 'High',np.where(df['Marks'] <20, 'Low', 'Medium'))
print(df)

   Marks category
0     10      Low
1     15      Low
2     20   Medium
3     25     High
4     30     High

### 190 You've been given a dataset with apartment area and price information. There's a noticeable non-linear relationship between area and price. To address this you intend to categorize them into 'High', 'Medium', and 'Low' groups. Prices above 3,000,000 are 'High', below 2,000,000 are 'Low', and between 2,000,000 and 3,000,000 are 'Medium'. Write a code to achieve this assuming that dataset has two columns named area and price.

In [14]:
import pandas as pd
import numpy as np
a = { 'Area': [500, 750, 1000, 1200, 1500],
'Price': [1500000, 2500000, 3000000, 3500000, 1800000]
}
df= pd.DataFrame(a)
df['Category'] = np.where(df['Price'] > 3000000, 'High',np.where(df['Price'] <2000000, 'Low', 'Medium'))
print(df)

   Area    Price Category
0   500  1500000      Low
1   750  2500000   Medium
2  1000  3000000   Medium
3  1200  3500000     High
4  1500  1800000      Low

## train_test_split()

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

df=pd.read_csv("auto-mpg.csv")

X = df[['weight']]
Y = df['cylinders']

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.5, random_state=2)
print(df.shape)

print("\n---------------------\n")
print(X_train.shape, X_test.shape)
print(Y_train.shape, Y_test.shape)

(398, 9)

---------------------

(199, 1) (199, 1)
(199,) (199,)

In [2]:


import pandas as pd
import numpy as np
data={
    "Name":["A","B","C","D","E","F"],
    "Gender":["Male","Female","Male","Female","Male","Female"],
     "Dept":["IT","HR","Sales","IT","HR","Sales"],
    "Age":[20,22,24,26,28,30],
    "Salary":[3000,4000,5000,6000,7000,8000],
    }
df=pd.DataFrame(data)
df

  Name  Gender   Dept  Age  Salary
0    A    Male     IT   20    3000
1    B  Female     HR   22    4000
2    C    Male  Sales   24    5000
3    D  Female     IT   26    6000
4    E    Male     HR   28    7000
5    F  Female  Sales   30    8000

In [4]:
pd.get_dummies(df,columns=["Gender","Dept"])

  Name  Age  Salary  Gender_Female  Gender_Male  Dept_HR  Dept_IT  Dept_Sales
0    A   20    3000          False         True    False     True       False
1    B   22    4000           True        False     True    False       False
2    C   24    5000          False         True    False    False        True
3    D   26    6000           True        False    False     True       False
4    E   28    7000          False         True     True    False       False
5    F   30    8000           True        False    False    False        True

In [6]:
pd.get_dummies(df,columns=["Gender","Dept"],drop_first=True)

  Name  Age  Salary  Gender_Male  Dept_IT  Dept_Sales
0    A   20    3000         True     True       False
1    B   22    4000        False    False       False
2    C   24    5000         True    False        True
3    D   26    6000        False     True       False
4    E   28    7000         True    False       False
5    F   30    8000        False    False        True

In [8]:
pd.get_dummies(df,drop_first=True)

,Age,Salary,Name_B,Name_C,Name_D,Name_E,Name_F,Gender_Male,Dept_IT,Dept_Sales
0,20,3000,False,False,False,False,False,True,True,False
1,22,4000,True,False,False,False,False,False,False,False
2,24,5000,False,True,False,False,False,True,False,True
3,26,6000,False,False,True,False,False,False,True,False
4,28,7000,False,False,False,True,False,True,False,False
5,30,8000,False,False,False,False,True,False,False,True

In [10]:
pd.get_dummies(df,columns=["Gender","Dept"],drop_first=False)

  Name  Age  Salary  Gender_Female  Gender_Male  Dept_HR  Dept_IT  Dept_Sales
0    A   20    3000          False         True    False     True       False
1    B   22    4000           True        False     True    False       False
2    C   24    5000          False         True    False    False        True
3    D   26    6000           True        False    False     True       False
4    E   28    7000          False         True     True    False       False
5    F   30    8000           True        False    False    False        True

In [12]:
pd.get_dummies(df,columns=["Gender","Dept"],drop_first=True)

  Name  Age  Salary  Gender_Male  Dept_IT  Dept_Sales
0    A   20    3000         True     True       False
1    B   22    4000        False    False       False
2    C   24    5000         True    False        True
3    D   26    6000        False     True       False
4    E   28    7000         True    False       False
5    F   30    8000        False    False        True

In [14]:
df["bonus"]=np.where(df["Salary"]>5000,"good","bad")
df

  Name  Gender   Dept  Age  Salary bonus
0    A    Male     IT   20    3000   bad
1    B  Female     HR   22    4000   bad
2    C    Male  Sales   24    5000   bad
3    D  Female     IT   26    6000  good
4    E    Male     HR   28    7000  good
5    F  Female  Sales   30    8000  good